/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Double-sliding-frames.gltf --transform 
Files: Double-sliding-frames.gltf [4.59KB] > D:\React native projects\UnityPOC\src\assets\models\Double-sliding-frames-transformed.glb [987.82KB] (-21421%)
*/

import React from 'react';
import {useGLTF} from '@react-three/drei/native';
import window from './Double-sliding-frames-transformed.glb';

export function Model(props) {
  const {nodes, materials} = useGLTF(window);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Window_frame001.geometry}
        material={materials.Bricks}
        position={[-0.025, -1.329, 1.075]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.002}
      />
      <mesh
        geometry={nodes.Window_rail001.geometry}
        material={materials.Mat_3}
        position={[-0.017, -1.111, 1.094]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.002}
      />
    </group>
  );
}

useGLTF.preload(window);
